/**
 * VERITAS‑1.0‑DEMO
 * File: server.js
 * Purpose: Backend entrypoint for the VERITAS demo environment.
 *          Starts the Express server, configures middleware, and mounts
 *          all backend routes including the Panasonic G2 ingestion module.
 *
 * Notes:
 * - This file must remain minimal and operator‑grade.
 * - All business logic belongs in dedicated modules (for example, g2_ingestion.js).
 * - This file only wires modules together and exposes API (application programming interface) endpoints.
 *
 * Updated: 2026‑05‑27
 * Updated by: Microsoft Copilot (per Nils’ ground rules)
 */

const express = require('express');      // Web framework for routing and server creation
const cors = require('cors');            // Cross‑origin resource sharing middleware
const bodyParser = require('body-parser'); // JSON request body parsing middleware

// === Import Panasonic G2 ingestion router ===
// This module enumerates all ingestible files under the SCANS directory.
const g2IngestionRouter = require('./g2_ingestion');

// === Create Express application instance ===
const app = express();

// === Port configuration ===
// The demo backend runs on port 4000 as standard.
const PORT = 4000;

// === Global middleware configuration ===
app.use(cors());               // Enable cross‑origin requests
app.use(bodyParser.json());    // Parse JSON request bodies

/**
 * === Health check endpoint ===
 * Purpose:
 * - Allows frontend and operators to verify that the backend is running.
 * - Returns a simple JSON payload confirming operational status.
 *
 * Route:
 *   GET /api/status
 */
app.get('/api/status', (req, res) => {
  res.json({
    status: 'VERITAS backend running',
    port: PORT
  });
});

/**
 * === Login endpoint (demo edition) ===
 * Purpose:
 * - Provides a minimal authentication mechanism for the demo.
 * - Validates a single hard‑coded PIN (personal identification number).
 *
 * Route:
 *   POST /api/login
 *
 * Notes:
 * - This is NOT production authentication.
 * - This is intentionally simple for demonstration purposes.
 */
app.post('/api/login', (req, res) => {
  const { pin } = req.body;

  // Demo‑grade validation only
  if (pin === '1234') {
    return res.json({
      success: true,
      message: 'Access granted'
    });
  }

  return res.status(401).json({
    success: false,
    message: 'Invalid PIN'
  });
});

/**
 * === Panasonic G2 ingestion route ===
 *
 * Purpose:
 * - Exposes the ingestion snapshot generated by g2_ingestion.js.
 * - Allows the frontend to retrieve a structured list of all files
 *   under the SCANS directory (JPEG, PNG, TIFF, PDF, BMP).
 *
 * Route:
 *   GET /api/g2/ingest
 *
 * Notes:
 * - This is a read‑only endpoint.
 * - All ingestion logic resides in g2_ingestion.js.
 */
app.use('/api/g2/ingest', g2IngestionRouter);

/**
 * === Placeholder module routes (demo edition) ===
 * These routes simulate the presence of additional VERITAS modules.
 * They return static JSON payloads confirming module availability.
 *
 * Routes:
 *   /api/evidence
 *   /api/nuar
 *   /api/simulation
 */
app.use('/api/evidence', (req, res) => {
  res.json({ module: 'Evidence', status: 'OK' });
});

app.use('/api/nuar', (req, res) => {
  res.json({ module: 'NUAR', status: 'OK' });
});

app.use('/api/simulation', (req, res) => {
  res.json({ module: 'Simulation', status: 'OK' });
});

/**
 * === Start the backend server ===
 * Purpose:
 * - Binds the Express application to the configured port.
 * - Outputs a console message confirming operational status.
 */
app.listen(PORT, () => {
  console.log(`VERITAS backend running on http://localhost:${PORT}`);
});

